#include "blorb.h"
#include "settings.h"

#include <algorithm>
#include <chrono>
#include <ctime>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>

namespace fs = std::filesystem;
using namespace std;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

void Blorb::writeU32BE(ostream& out, uint32_t v) {
    char buf[4] = {
        char((v >> 24) & 0xFF),
        char((v >> 16) & 0xFF),
        char((v >>  8) & 0xFF),
        char( v        & 0xFF)
    };
    out.write(buf, 4);
}

vector<char> Blorb::readFile(const string& path) {
    ifstream f(path, ios::binary | ios::ate);
    if(!f.is_open())
        throw runtime_error("Cannot open file: " + path);
    streamsize sz = f.tellg();
    f.seekg(0, ios::beg);
    vector<char> buf(sz);
    if(!f.read(buf.data(), sz))
        throw runtime_error("Read error: " + path);
    return buf;
}

string Blorb::makeMemberName(const string& stem, const string& ext) {
    // Build camelCase from stem (treating hyphens/underscores as word breaks)
    // then append the capitalised extension as a suffix.
    string result;
    bool nextUpper = false;
    for(char c : stem) {
        if(c == '-' || c == '_' || c == ' ') {
            nextUpper = true;
        } else {
            result += (nextUpper && !result.empty()) ? (char)toupper(c) : c;
            nextUpper = false;
        }
    }
    // Append capitalised extension (e.g. "png" → "Png")
    if(!ext.empty()) {
        string e = ext;
        e[0] = (char)toupper(e[0]);
        result += e;
    }
    return result;
}

// ---------------------------------------------------------------------------
// Phase 1 — Asset scan
// ---------------------------------------------------------------------------

vector<BlorbAsset> Blorb::scanAssets(const string& assetDir) {
    vector<BlorbAsset> pictures, sounds;

    if(!fs::exists(assetDir) || !fs::is_directory(assetDir)) {
        cerr << "Blorb: asset directory '" << assetDir << "' not found — skipping.\n";
        return {};
    }

    for(auto& entry : fs::directory_iterator(assetDir)) {
        if(!entry.is_regular_file()) continue;
        string ext = entry.path().extension().string();
        // Lowercase the extension for matching
        string extLower = ext;
        transform(extLower.begin(), extLower.end(), extLower.begin(), ::tolower);
        if(extLower.size() > 0 && extLower[0] == '.') extLower = extLower.substr(1);

        string stem = entry.path().stem().string();
        string name = makeMemberName(stem, extLower);

        if(extLower == "png" || extLower == "jpg" || extLower == "jpeg") {
            pictures.push_back({ name, entry.path().string(), 0, true });
        } else if(extLower == "aiff" || extLower == "aif") {
            sounds.push_back({ name, entry.path().string(), 0, false });
        }
    }

    // Sort each group alphabetically by name
    auto byName = [](const BlorbAsset& a, const BlorbAsset& b){ return a.name < b.name; };
    sort(pictures.begin(), pictures.end(), byName);
    sort(sounds.begin(),   sounds.end(),   byName);

    // Assign globally sequential IDs: pictures first, then sounds
    vector<BlorbAsset> all;
    int id = 1;
    for(auto& a : pictures) { a.resourceId = id++; all.push_back(a); }
    for(auto& a : sounds)   { a.resourceId = id++; all.push_back(a); }
    return all;
}

void Blorb::writeEnumFile(const vector<BlorbAsset>& assets,
                          const string& outputBglPath,
                          const string& sourceFileName) {
    ofstream out(outputBglPath);
    if(!out.is_open()) {
        cerr << "Blorb: cannot write enum file '" << outputBglPath << "'\n";
        return;
    }

    out << "// Auto-generated by beguiler blorbifier — do not edit\n";
    out << "// Blorb asset map for: " << sourceFileName << "\n";

    if(assets.empty()) {
        out << "// (no assets found)\n";
        out << "enum eAssets { _noAssets = 0 }\n";
        return;
    }

    out << "enum eAssets {\n";
    for(size_t i = 0; i < assets.size(); i++) {
        out << "    " << assets[i].name << " = " << assets[i].resourceId;
        if(i + 1 < assets.size()) out << ",";
        out << "\n";
    }
    out << "}\n";
    cout << "Blorb: wrote asset enum to '" << outputBglPath << "' ("
         << assets.size() << " asset(s))\n";
}

// ---------------------------------------------------------------------------
// Phase 2 — IFF/IFRS assembly
// ---------------------------------------------------------------------------

bool Blorb::build(const string& storyFile,
                  const string& blorbOutPath,
                  const vector<BlorbAsset>& assets,
                  const string& copyright,
                  bool isGlulx,
                  const Metadata& meta) {
    // Load story file
    vector<char> storyData;
    try {
        storyData = readFile(storyFile);
    } catch(const exception& e) {
        cerr << "Blorb: " << e.what() << "\n";
        return true;
    }

    // Load all asset data up front
    struct AssetData { const BlorbAsset* asset; vector<char> data; };
    vector<AssetData> assetDatas;
    for(auto& a : assets) {
        try {
            assetDatas.push_back({ &a, readFile(a.filePath) });
        } catch(const exception& e) {
            cerr << "Blorb: " << e.what() << " — skipping\n";
        }
    }

    // Helper: round up to even (IFF requires even chunk sizes)
    auto pad = [](size_t n) -> size_t { return n + (n & 1); };

    // Build the copyright string
    string copyrightStr = copyright;
    if(copyrightStr.empty() && !meta.author.empty()) {
        auto now = chrono::system_clock::to_time_t(chrono::system_clock::now());
        tm* t = localtime(&now);
        copyrightStr = meta.author + " " + to_string(1900 + t->tm_year);
    }

    // -----------------------------------------------------------------------
    // Two-pass approach: accumulate chunks in memory, then write final file.
    // Pass 1: compute chunk sizes and RIdx offsets.
    // Pass 2: write the file.
    // -----------------------------------------------------------------------
    struct Chunk {
        string   type;          // 4-char IFF type
        vector<char> data;
        // Resource index entry (empty type = not a resource)
        string   usage;         // "Pict", "Snd ", "Exec" or ""
        uint32_t resNum = 0;
    };

    vector<Chunk> chunks;

    // (c) copyright chunk (optional)
    if(!copyrightStr.empty()) {
        Chunk c; c.type = "(c) ";
        c.data.assign(copyrightStr.begin(), copyrightStr.end());
        chunks.push_back(std::move(c));
    }

    // AUTH chunk (optional)
    if(!meta.author.empty()) {
        Chunk c; c.type = "AUTH";
        c.data.assign(meta.author.begin(), meta.author.end());
        chunks.push_back(std::move(c));
    }

    // IFmd chunk — iFiction XML metadata (Treaty of Babel rev 12)
    if(!meta.ifid.empty()) {
        string fmt = isGlulx ? "glulx" : "zcode";
        string xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                     "<ifiction version=\"1.0\" xmlns=\"http://babel.ifarchive.org/protocol/iFiction/\">\n"
                     "  <story>\n"
                     "    <identification>\n"
                     "      <ifid>" + meta.ifid + "</ifid>\n"
                     "      <format>" + fmt + "</format>\n"
                     "    </identification>\n"
                     "    <bibliographic>\n"
                     "      <title>" + (meta.title.empty() ? "Untitled" : meta.title) + "</title>\n"
                     "      <author>" + (meta.author.empty() ? "Anonymous" : meta.author) + "</author>\n";
        if(!meta.language.empty())       xml += "      <language>" + meta.language + "</language>\n";
        if(!meta.headline.empty())       xml += "      <headline>" + meta.headline + "</headline>\n";
        if(!meta.firstPublished.empty()) xml += "      <firstpublished>" + meta.firstPublished + "</firstpublished>\n";
        if(!meta.genre.empty())          xml += "      <genre>" + meta.genre + "</genre>\n";
        if(!meta.description.empty())    xml += "      <description>" + meta.description + "</description>\n";
        if(!meta.series.empty())         xml += "      <series>" + meta.series + "</series>\n";
        if(meta.seriesNumber > 0)        xml += "      <seriesnumber>" + to_string(meta.seriesNumber) + "</seriesnumber>\n";
        if(!meta.forgiveness.empty())    xml += "      <forgiveness>" + meta.forgiveness + "</forgiveness>\n";
        xml += "    </bibliographic>\n"
               "    <colophon>\n"
               "      <generator>Beguile</generator>\n"
               "      <generatorversion>" + to_string(BEGUILER_VERSION) + "</generatorversion>\n"
               "      <originated>" + fmt + "</originated>\n"
               "    </colophon>\n"
               "  </story>\n"
               "</ifiction>\n";
        Chunk c; c.type = "IFmd";
        c.data.assign(xml.begin(), xml.end());
        chunks.push_back(std::move(c));
    }

    // Asset chunks (pictures and sounds)
    for(auto& ad : assetDatas) {
        Chunk c;
        if(ad.asset->isPicture) {
            // Detect PNG vs JPEG from file header
            bool isPng = (ad.data.size() >= 8 &&
                          (unsigned char)ad.data[0] == 0x89 &&
                          ad.data[1]=='P' && ad.data[2]=='N' && ad.data[3]=='G');
            c.type  = isPng ? "PNG " : "JPEG";
            c.usage = "Pict";
        } else {
            c.type  = "AIFF";
            c.usage = "Snd ";
        }
        c.resNum = (uint32_t)ad.asset->resourceId;
        c.data   = ad.data;
        chunks.push_back(std::move(c));
    }

    // Story file chunk (always last, resource number 0)
    {
        Chunk c;
        c.type   = isGlulx ? "GLUL" : "ZCOD";
        c.usage  = "Exec";
        c.resNum = 0;
        c.data   = storyData;
        chunks.push_back(std::move(c));
    }

    // Count resource chunks for RIdx
    uint32_t resourceCount = 0;
    for(auto& c : chunks) if(!c.usage.empty()) resourceCount++;

    // RIdx chunk size: 4 (count field) + 12 * count
    uint32_t ridxDataSize  = 4 + 12 * resourceCount;
    uint32_t ridxChunkSize = 8 + ridxDataSize; // tag + length + data

    // Compute absolute file offsets for each chunk.
    // Blorb spec: RIdx offsets are byte positions from the start of the file.
    // Layout: FORM header (12 bytes) | RIdx chunk | other chunks...
    uint32_t offset = 12 + ridxChunkSize; // 12 = "FORM" + size + "IFRS"
    // Pad RIdx chunk itself to even
    if(ridxDataSize & 1) offset++;

    struct ChunkInfo { uint32_t offset; uint32_t dataSize; };
    vector<ChunkInfo> infos;
    for(auto& c : chunks) {
        infos.push_back({ offset, (uint32_t)c.data.size() });
        uint32_t chunkTotal = 8 + (uint32_t)pad(c.data.size());
        offset += chunkTotal;
    }

    // Total FORM content size (after "FORM <size> IFRS"):
    // = ridxChunkSize (padded) + sum of all other chunks (padded)
    uint32_t formContentSize = 4 + ((ridxDataSize & 1) ? ridxChunkSize + 1 : ridxChunkSize); // 4 = "IFRS"
    for(auto& info : infos)
        formContentSize += 8 + (uint32_t)pad(info.dataSize);

    // Write the file
    ofstream f(blorbOutPath, ios::binary);
    if(!f.is_open()) {
        cerr << "Blorb: cannot create '" << blorbOutPath << "'\n";
        return true;
    }

    // FORM header
    f.write("FORM", 4);
    writeU32BE(f, formContentSize);
    f.write("IFRS", 4);

    // RIdx chunk
    f.write("RIdx", 4);
    writeU32BE(f, ridxDataSize);
    writeU32BE(f, resourceCount);
    for(size_t i = 0; i < chunks.size(); i++) {
        if(chunks[i].usage.empty()) continue;
        string usage = chunks[i].usage;
        while(usage.size() < 4) usage += ' ';
        f.write(usage.c_str(), 4);
        writeU32BE(f, chunks[i].resNum);
        writeU32BE(f, infos[i].offset);
    }
    if(ridxDataSize & 1) f.put('\0'); // pad to even

    // All other chunks
    for(size_t i = 0; i < chunks.size(); i++) {
        string type = chunks[i].type;
        while(type.size() < 4) type += ' ';
        f.write(type.c_str(), 4);
        writeU32BE(f, infos[i].dataSize);
        if(!chunks[i].data.empty())
            f.write(chunks[i].data.data(), (streamsize)chunks[i].data.size());
        if(infos[i].dataSize & 1) f.put('\0'); // pad to even
    }

    f.close();
    cout << "Blorb: wrote '" << blorbOutPath << "' ("
         << assetDatas.size() << " asset(s) + story)\n";
    return false;
}
