#!/usr/bin/env python3
"""Field trials: small programs written against the Inform 6 standard library to exercise the compiler the
way an author's code does. They are hardening tests, not games or examples.

Each trial is two files in tests/fieldTrials/:

  <name>.bgl     the program: complete, with its own #beguilerSettings (target, includePaths)
  <name>.trial   the commands to type and what each must print:

      Room A                      <- optional opening text: every line must appear before the first prompt
      > take key                  <- a command
      Taken.                      <- what it must print (blank lines ignored, trailing spaces ignored)
      > i
      You're carrying:
        a brass key

  On Glulx, text printed to a window other than the main one is a line of its own, `[win N] text`.
  A line `#grids` at the top also captures text-grid windows (the status line): a snapshot is printed
  as `[grid N]` followed by `|line|` rows wherever the story waits for input. Window and grid ids are
  renumbered 1, 2, … in order of first appearance, since the interpreter's ids vary from run to run.

  Files whose names start with `_` (generated by a build, such as `_blorbAssets.bgl`) are not trials.

The program is compiled by beguiler (which hands off to Inform 6), then run with the commands on stdin.

Usage: field_trials.py [--only NAME] [--keep DIR] [--show]
  --show   print each trial's full transcript (to write or check a .trial)
Exit status is non-zero when any trial fails.
"""
import argparse, concurrent.futures, glob, os, re, shutil, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
TRIALS = os.path.join(ROOT, 'tests', 'fieldTrials')
BEGUILER = os.path.join(ROOT, 'beguiler')
ZVM = os.environ.get('ZVM') or shutil.which('zvm') or os.path.join(ROOT, '..', 'beguilex', 'node_modules', '.bin', 'zvm')
GLULX_RUN = os.path.join(HERE, 'glulx-run.js')


def run(cmd, cwd, stdin='', env=None):
    try:
        p = subprocess.run(cmd, cwd=cwd, input=stdin, capture_output=True, text=True, encoding='utf-8',
                           errors='replace', timeout=60, env=env)
        return p.returncode, p.stdout + p.stderr
    except subprocess.TimeoutExpired:
        return -1, 'TIMEOUT'


def read_trial(path):
    """(opening lines, [(command, expected lines)], grids?)"""
    opening, steps, grids = [], [], False
    for raw in open(path, encoding='utf-8').read().split('\n'):
        line = raw.rstrip()
        if line == '#grids':
            grids = True
        elif line.startswith('>'):
            steps.append((line[1:].strip(), []))
        elif line.strip():
            (steps[-1][1] if steps else opening).append(line)
    return opening, steps, grids


def split_transcript(text):
    """Text before the first prompt, and the text each command printed (prompt lines are `>command`)."""
    blocks, cur, cmd = [], [], None
    for raw in text.split('\n'):
        line = raw.rstrip()
        m = re.match(r'^>\s?(.*)$', line)
        if m:
            blocks.append((cmd, cur))
            cmd, cur = m.group(1).strip(), []
        elif line.strip():
            cur.append(line)
    blocks.append((cmd, cur))
    return blocks[0][1], blocks[1:]


def renumber_windows(text):
    """`[win 1234]` / `[grid 1234]` → `[win 1]`, `[win 2]`, … in order of first appearance."""
    ids = {}
    def sub(m):
        key = (m.group(1), m.group(2))
        if key not in ids:
            ids[key] = sum(1 for k in ids if k[0] == m.group(1)) + 1
        return f'[{m.group(1)} {ids[key]}]'
    return re.sub(r'\[(win|grid) (\d+)\]', sub, text)


def check(path, keep, show):
    name = os.path.splitext(os.path.basename(path))[0]
    trial = os.path.splitext(path)[0] + '.trial'
    if not os.path.exists(trial):
        return name, 'NO-TRIAL', f'{os.path.basename(trial)} is missing', ''
    opening, steps, grids = read_trial(trial)
    work = os.path.join(keep or tempfile.mkdtemp(prefix='trial-'), name)
    os.makedirs(work, exist_ok=True)
    code, out = run([BEGUILER, '-o', work, path], os.path.dirname(path))
    stories = [f for f in os.listdir(work) if f.endswith(('.z5', '.z8', '.ulx'))]
    # Inform 6 can leave a story behind after reporting errors, so its error count decides too.
    if not stories or re.search(r'Compiled with \d+ errors?', out) or 'Error running I6' in out:
        err = next((l for l in out.split('\n') if 'ERROR' in l or 'Error' in l), out.strip()[-300:])
        return name, 'COMPILE-FAIL', re.sub(r'^.*?/(?=[^/]*\.(bgl|inf)[:(])', '', err.strip())[:300], out
    story = os.path.join(work, stories[0])
    stdin = '\n'.join(c for c, _ in steps) + '\n'
    if story.endswith('.ulx'):
        env = dict(os.environ, GLULX_RUN_WINDOWS='1')
        if grids:
            env['GLULX_RUN_GRIDS'] = '1'
        code, out = run(['node', GLULX_RUN, story], work, stdin, env)
        out = renumber_windows(out)
    else:
        code, out = run([ZVM, story], work, stdin)
    if show:
        print(f'===== {name}\n{out}')
    if 'Programming error' in out or 'fatal error' in out.lower() or code == -1:
        bad = next((l for l in out.split('\n') if 'error' in l.lower() or 'TIMEOUT' in l), '')
        return name, 'RUN-FAIL', bad.strip()[:300], out
    got_opening, got_steps = split_transcript(out)
    problems = []
    for line in opening:
        if not any(line.strip() == g.strip() for g in got_opening):
            problems.append(f'opening: missing "{line.strip()}"')
    for i, (cmd, want) in enumerate(steps):
        if i >= len(got_steps):
            problems.append(f'> {cmd}: the story stopped before this command')
            break
        got_cmd, got = got_steps[i]
        w = [l.rstrip() for l in want]
        g = [l.rstrip() for l in got]
        if w != g:
            problems.append(f'> {cmd}: want {w!r}, got {g!r}')
    if problems:
        return name, 'MISMATCH', '\n      '.join(problems)[:1500], out
    return name, 'PASS', '', out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--only')
    ap.add_argument('--keep')
    ap.add_argument('--show', action='store_true')
    a = ap.parse_args()
    paths = sorted(p for p in glob.glob(os.path.join(TRIALS, '*.bgl')) if not os.path.basename(p).startswith('_'))
    if a.only:
        paths = [p for p in paths if os.path.splitext(os.path.basename(p))[0] == a.only]
    with concurrent.futures.ThreadPoolExecutor(os.cpu_count() or 4) as ex:
        results = list(ex.map(lambda p: check(p, a.keep, a.show), paths))
    counts = {}
    for name, status, detail, _ in results:
        counts[status] = counts.get(status, 0) + 1
        if status != 'PASS':
            print(f'  {status}: {name} — {detail}')
    print('Field trials: ' + (', '.join(f'{v} {k.lower()}' for k, v in sorted(counts.items())) or 'none'))
    sys.exit(0 if all(s == 'PASS' for _, s, _, _ in results) else 1)


if __name__ == '__main__':
    main()
